var lay_id = layer_get_id("Backgrounds_1")
var back_id = layer_background_get_id(lay_id)
var lay_id2 = layer_get_id("Backgrounds_2")
var back_id2 = layer_background_get_id(lay_id2)
var lay_id3 = layer_get_id("Backgrounds_3")
var back_id3 = layer_background_get_id(lay_id3)
if (global.panic == 1 && layer_background_get_sprite(back_id) == 1632)
    layer_background_sprite(back_id, 1631)
if (global.panic == 1 && layer_background_get_sprite(back_id) == 1629)
    layer_background_sprite(back_id, 1630)
if (global.panic == 1 && layer_background_get_sprite(back_id3) == 1634)
    layer_background_sprite(back_id3, 1635)
if (global.panic == 1 && layer_background_get_sprite(back_id) == 1595)
    layer_background_sprite(back_id, 1596)
if (global.panic == 1 && layer_background_get_sprite(back_id) == 1598)
    layer_background_sprite(back_id, 1599)
if (global.panic == 1 && layer_background_get_sprite(back_id2) == 1600)
    layer_background_sprite(back_id2, 1601)
if (global.panic == 1 && layer_background_get_sprite(back_id) == 1675)
    layer_background_sprite(back_id, 1676)
if (global.panic == 1 && layer_background_get_sprite(back_id2) == 1673)
    layer_background_sprite(back_id2, 1674)
if (global.panic == 1 && layer_background_get_sprite(back_id3) == 1671)
    layer_background_sprite(back_id3, 1672)
